// import styles from "../styles/Home.module.css";
import { Container, Main, InputBox, Button } from "./Register.styled";
import Head from "next/head";
import { auth } from "../../configs/firebase";
import { useEffect } from "react";
import {
  createUserWithEmailAndPassword,
  GoogleAuthProvider,
  signInWithPopup,
} from "firebase/auth";
import { useState } from "react";
import { useRouter } from "next/router";

export const Register = () => {
  const googleProvider = new GoogleAuthProvider();
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const signUp = () => {
    createUserWithEmailAndPassword(auth, email, password)
      .then((response) => {
        sessionStorage.setItem("Token", response.user.accessToken);
        router.push("/home");
      })
      .catch((err) => {
        alert("Email Already Exists");
        setEmail("");
        setPassword("");
      });
  };

  const signUpWithGoogle = () => {
    signInWithPopup(auth, googleProvider).then((response) => {
      sessionStorage.setItem("Token", response.user.accessToken);
      console.log(response.user.accessToken);
      router.push("/home");
    });
  };

  const login = () => {
    router.push("/login");
  };

  useEffect(() => {
    let token = sessionStorage.getItem("Token");

    if (token) {
      router.push("/home");
    }
  }, []);

  return (
    <Container>
      <Head>
        <title>Next CRUD AUTH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <h1>Register</h1>

        <InputBox
          placeholder="Email"
          onChange={(event) => setEmail(event.target.value)}
          value={email}
          type="email"
        />
        <InputBox
          placeholder="Password"
          onChange={(event) => setPassword(event.target.value)}
          value={password}
          type="password"
        />

        <Button onClick={signUp}>Sign Up</Button>
        <hr />
        <Button onClick={signUpWithGoogle}>Sign Up with Google</Button>
        <br />
        <div>
          <p>Já tem uma conta: </p>
          <Button onClick={login}>Log in</Button>
        </div>
      </Main>
    </Container>
  );
};
